version: "3"
services:
    mongodb:
        image: mongo
        ports:
            - 27017:27017
        networks:
            - champnetwork

    champ:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        depends_on:
            - mongodb
        networks:
            - champnetwork

networks:
    champnetwork:
